"""initial migration

Revision ID: 3511ead0c1f6
Revises: 
Create Date: 2025-04-29 00:32:55.363932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3511ead0c1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_key', type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_phone_key', ['phone'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('image_urls')

    # ### end Alembic commands ###
