"""fixed duplicate backref

Revision ID: 621a86586107
Revises: 53e1aa884984
Create Date: 2025-04-17 01:02:37.487793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621a86586107'
down_revision = '53e1aa884984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('price')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
