"""no longer reliant on temp data and added vector column

Revision ID: 8d6fb232258f
Revises: f1a3feccf3d9
Create Date: 2025-04-19 19:19:31.758921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d6fb232258f'
down_revision = 'f1a3feccf3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))
        batch_op.drop_column('image')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector', postgresql.ARRAY(sa.Float()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('vector')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
